# Generated by Django 2.0.6 on 2018-08-21 16:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180609_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
