# Generated by Django 2.0.6 on 2018-08-21 16:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiteshmapBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('alias', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('created', models.DateField()),
                ('modified', models.DateField()),
                ('is_published', models.BooleanField(default=True, help_text='Designates whether this blog is published. Unselect this instead of deleting blogs.', verbose_name='published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='MiteshmapBlogTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='', max_length=100)),
                ('blog_id', models.ManyToManyField(to='blog.MiteshmapBlog')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='MiteshmapBlogWebsites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(default='', max_length=255)),
                ('blog_id', models.ManyToManyField(to='blog.MiteshmapBlog')),
            ],
            options={
                'db_table': 'websites',
            },
        ),
    ]
