# Generated by Django 2.0.6 on 2018-09-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miteshmapblog',
            name='website',
        ),
        migrations.AddField(
            model_name='miteshmapblog',
            name='website',
            field=models.ManyToManyField(null=True, to='blog.MiteshmapBlogWebsites'),
        ),
    ]
