# Generated by Django 2.0.6 on 2018-09-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180920_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miteshmapblog',
            name='website',
            field=models.ManyToManyField(blank=True, to='blog.MiteshmapBlogWebsites'),
        ),
    ]
